---
title: "Final_project_script"
output: html_document
date: "2026-04-16"
---

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(lubridate)
library(here)
library(vip)          
library(xgboost)      
library(ranger)       
library(tidyverse)    
library(doParallel)   
library(shapviz)

set.seed(238472)

# ----------LOAD TRAINING DATA------------
train_trait <- read_csv("../data/training/training_trait.csv") %>% 
  clean_names() 
train_meta <- read_csv("../data/training/training_meta.csv") %>% 
  clean_names() 
train_soil <- read_csv("../data/training/training_soil.csv") %>% 
  clean_names()

# ----------FIXING SOIL SITE COLUMN---------------
train_soil <- train_soil %>%
  separate(site, into = c("site", "year"), sep = "_", remove = TRUE) %>%
  mutate(year = as.integer(year)) %>%
  group_by(site, year)

# -----------CLEAN META--------------
train_meta <- train_meta %>%
  mutate(previous_crop = str_to_lower(previous_crop)) %>%
  group_by(site, year)

# ------------AGGREGATE TRAITS-------------
train_trait_clean <- train_trait %>%
  mutate(
    date_planted = mdy(date_planted),
    date_harvested = mdy(date_harvested)
  ) %>%
  group_by(site, year, hybrid) %>%
  summarize(
    yield = mean(yield_mg_ha, na.rm = TRUE),
    grain_moisture = mean(grain_moisture, na.rm = TRUE),
    date_planted = min(date_planted, na.rm = TRUE),
    date_harvested = max(date_harvested, na.rm = TRUE),
    .groups = "drop"
  )

# -------------MERGE------------
train_full <- train_trait_clean %>%
  left_join(train_meta, by = c("site", "year")) %>%
  left_join(train_soil, by = c("site", "year"))

```


```{r}
# ----------LOAD TESTING DATA------------
test_meta <- read_csv("../data/testing/testing_meta.csv") %>% 
  clean_names()
test_soil <- read_csv("../data/testing/testing_soil.csv") %>% 
  clean_names()
test_sub  <- read_csv("../data/testing/testing_submission.csv") %>% 
  clean_names()

# ----------FIXING SOIL SITE COLUMN---------------
test_soil <- test_soil %>%
  separate(site, into = c("site", "year"), sep = "_") %>%
  mutate(year = as.integer(year)) %>%
  group_by(site, year) 

# -----------CLEAN META--------------
test_meta <- test_meta %>%
  mutate(previous_crop = str_to_lower(previous_crop)) %>%
  group_by(site, year)

# -------------MERGE------------
test_full <- test_sub %>% 
  rename(yield = yield_mg_ha) %>%
  left_join(test_meta, by = c("site", "year")) %>%
  left_join(test_soil, by = c("site", "year"))

```

```{r}
library(daymetr)
library(slider)

#----------CREATE PLANTING AND HARVEST WINDOWS (BY SITE)------
site_calendar <- train_full %>%
  mutate(
    plant_doy = yday(date_planted),
    harvest_doy = yday(date_harvested)
  ) %>%
  group_by(site) %>%
  summarize(
    typical_plant_doy = round(median(plant_doy, na.rm = TRUE)),
    typical_harvest_doy = round(median(harvest_doy, na.rm = TRUE)),
    .groups = "drop"
  )

#-----------ADDING P/H WINDOWS TO TESTING AND TRAINING DATA------------
train_full <- train_full %>%
  mutate(
    plant_doy = yday(date_planted),
    harvest_doy = yday(date_harvested)
  ) %>%
  left_join(site_calendar, by = "site")

test_full <- test_full %>%
  left_join(site_calendar, by = "site") %>%
  mutate(
    plant_doy = typical_plant_doy,
    harvest_doy = typical_harvest_doy
  )
```

```{r}
#-----FILLING IN MISSING DOY VALUES-------
global_plant_doy <- round(median(train_full$plant_doy, na.rm = TRUE))
global_harvest_doy <- round(median(train_full$harvest_doy, na.rm = TRUE))

#------ADDING MISSING VALUES TO TRAINING AND TESTING DATA-------
train_full <- train_full %>%
  mutate(
    plant_doy = coalesce(plant_doy, typical_plant_doy, global_plant_doy),
    harvest_doy = coalesce(harvest_doy, typical_harvest_doy, global_harvest_doy)
  )
test_full <- test_full %>%
  mutate(
    plant_doy = coalesce(plant_doy, typical_plant_doy, global_plant_doy),
    harvest_doy = coalesce(harvest_doy, typical_harvest_doy, global_harvest_doy)
  )
#-------CREATING A SITE-YEAR LIST-------
all_site_years <- bind_rows(
  train_full %>% distinct(site, year, latitude, longitude, plant_doy, harvest_doy),
  test_full %>% distinct(site, year, latitude, longitude, plant_doy, harvest_doy)
) %>%
  arrange(site, year)
```

```{r}
#---------FIXING ANY POS LONGITUDE NUMBERS (NORTH AMERICA HAS NEG LONGITUDE)--------
all_site_years <- all_site_years %>%
  mutate(
    longitude = if_else(longitude > 0 & longitude < 180, -longitude, longitude)
  )
```


```{r}
#----------PULLING DAYMET DATA----------
get_daymet_one <- function(site, year, lat, lon) {
  tryCatch({
    out <- download_daymet(
      site = paste0(site, "_", year),
      lat = lat,
      lon = lon,
      start = year,
      end = year,
      internal = TRUE,
      silent = TRUE
    )
#----------SKIP LON/LAT NOT IN THE USA------------
    out$data %>%
      as_tibble() %>%
      mutate(site = site, year = year)

  }, error = function(e) {
    message(paste("Skipping:", site, year))
    return(NULL)
  })
}

weather_list <- purrr::pmap(
  all_site_years,
  ~ get_daymet_one(site = ..1, year = ..2, lat = ..3, lon = ..4)
)

weather_daily <- bind_rows(weather_list)
```

```{r}
#------------ENGINEERING WEATHER VARIABLES------------
weather_daily <- weather_daily %>%
  mutate(
    tmean = (tmax..deg.c. + tmin..deg.c.) / 2,
    tmax_cap = pmin(tmax..deg.c., 30),
    tmin_cap = pmax(tmin..deg.c., 10),
    gdd10_30 = pmax(((tmax_cap + tmin_cap) / 2) - 10, 0),
    hot_day_32 = as.integer(tmax..deg.c. > 32),
    hot_night_21 = as.integer(tmin..deg.c. > 21),
    dry_day = as.integer(prcp..mm.day. < 1),
    rad_mj_m2 = (srad..W.m.2. * dayl..s.) / 1e6
  )
```

```{r}
#-----------SUMMARIZE WEATHER VARIABLES------------
weather_features <- weather_daily %>%
  mutate(
    tmean = (tmax..deg.c. + tmin..deg.c.) / 2,
    gdd = pmax(tmean - 10, 0),
    hot_days = as.integer(tmax..deg.c. > 32),
    hot_nights = as.integer(tmin..deg.c. > 21),
    dry_day = as.integer(prcp..mm.day. < 1),
    rad_mj_m2 = (srad..W.m.2. * dayl..s.) / 1e6
  ) %>%
  group_by(site, year) %>%
  summarize(
    mean_temp = mean(tmean, na.rm = TRUE),
    max_temp = max(tmax..deg.c., na.rm = TRUE),
    min_temp = min(tmin..deg.c., na.rm = TRUE),

    total_prcp = sum(prcp..mm.day., na.rm = TRUE),
    rain_days = sum(prcp..mm.day. >= 1, na.rm = TRUE),

    hot_days = sum(hot_days, na.rm = TRUE),
    hot_nights = sum(hot_nights, na.rm = TRUE),

    gdd = sum(gdd, na.rm = TRUE),
    total_radiation = sum(rad_mj_m2, na.rm = TRUE),
    mean_vp = mean(vp..Pa., na.rm = TRUE),

    .groups = "drop"
  )
```

```{r}
#-------ADDING WEATHER TO TRAINING AND TESTING DATA-------
train_full <- train_full %>%
  left_join(weather_features, by = c("site", "year"))

test_full <- test_full %>%
  left_join(weather_features, by = c("site", "year"))
```

```{r}
#--------CREATING NEW DIRECTORY FOR FULL DATA----------
dir.create("../data/processed")

#-----------SAVING THE FINISHED AND CLEAN DATA---------
write_csv(train_full, "../data/processed/train_full_weather.csv")
write_csv(test_full, "../data/processed/test_full_weather.csv")
```

```{r}
#--------LOADING FINISHED DATA SETS-------
train_full <- read_csv("../data/processed/train_full_weather.csv")
test_full  <- read_csv("../data/processed/test_full_weather.csv")
```

```{r}
#-------USING 2023 AS A TEST SET-------
train_dev <- train_full %>%
  filter(year <= 2023)

test_2023 <- train_full %>%
  filter(year == 2023)
```

```{r}
train_full <- train_full %>%
  mutate(
    site = as.character(site),
    hybrid = as.character(hybrid),
    previous_crop = as.character(previous_crop)
  )

test_full <- test_full %>%
  mutate(
    site = as.character(site),
    hybrid = as.character(hybrid),
    previous_crop = as.character(previous_crop)
  )

train_dev <- train_full %>%
  filter(year <= 2022) %>%
  mutate(
    site = as.character(site),
    hybrid = as.character(hybrid),
    previous_crop = as.character(previous_crop)
  )

test_2023 <- train_full %>%
  filter(year == 2023) %>%
  mutate(
    site = as.character(site),
    hybrid = as.character(hybrid),
    previous_crop = as.character(previous_crop)
  )
```


```{r}
library(recipes)

#---------CREATING THE RECIPES---------
corn_recipe_xgb <- recipe(yield ~ ., data = train_dev) %>%
  step_rm(date_planted, date_harvested) %>%
  step_impute_median(all_numeric_predictors()) %>%
  step_novel(all_nominal_predictors()) %>%
  step_unknown(all_nominal_predictors()) %>%
  step_dummy(all_nominal_predictors())

corn_recipe_rf <- recipe(yield ~ ., data = train_dev) %>%
  step_rm(date_planted, date_harvested) %>%
  step_impute_median(all_numeric_predictors()) %>%
  step_novel(all_nominal_predictors()) %>%
  step_unknown(all_nominal_predictors()) %>%
  step_dummy(all_nominal_predictors())

svm_recipe <- recipe(yield ~ ., data = train_dev) %>%
  step_rm(date_planted, date_harvested) %>%
  step_impute_median(all_numeric_predictors()) %>%
  step_dummy(all_nominal_predictors()) %>%
  step_normalize(all_numeric_predictors())
```

```{r}
library(tidymodels)

#---------FITTING XGBOOST------------
xgb_spec <- boost_tree(
  trees = 800,
  tree_depth = 6,
  learn_rate = 0.02,
  min_n = 5,
  loss_reduction = 0,
  sample_size = 0.8,
  mtry = 10
) %>%
  set_engine("xgboost") %>%
  set_mode("regression")

xgb_wf <- workflow() %>%
  add_recipe(corn_recipe_xgb) %>%
  add_model(xgb_spec)

xgb_fit <- fit(xgb_wf, data = train_dev)

xgb_pred_2023 <- predict(xgb_fit, test_2023) %>%
  bind_cols(test_2023 %>% select(site, year, hybrid, yield))

xgb_metrics <- metrics(xgb_pred_2023, truth = yield, estimate = .pred)
xgb_metrics
```
```{r}
#-----------FITTING RANDOM FOREST (ADD MORE TREES WHEN SCRIPT FINALIZED)------------
rf_spec <- rand_forest(
  trees = 300,
  mtry = 10,
  min_n = 5
) %>%
  set_engine("ranger") %>%
  set_mode("regression")

rf_wf <- workflow() %>%
  add_recipe(corn_recipe_rf) %>%
  add_model(rf_spec)

rf_fit <- fit(rf_wf, data = train_dev)

rf_pred_2023 <- predict(rf_fit, test_2023) %>%
  bind_cols(test_2023 %>% 
              select(site, year, hybrid, yield))

rf_metrics <- metrics(rf_pred_2023, truth = yield, estimate = .pred)
rf_metrics
```

```{r}

#--------------FITTING SUPPORT VECTOR MODEL (SVM)----------------
library(tidyverse)
library(tidymodels)
library(kernlab)

svm_spec <- svm_rbf(
  cost = 1,
  rbf_sigma = 0.01
) %>%
  set_engine("kernlab") %>%
  parsnip::set_mode("regression")

svm_wf <- workflow() %>%
  add_recipe(svm_recipe) %>%
  add_model(svm_spec)

svm_fit <- fit(svm_wf, data = train_dev)

svm_pred_2023 <- predict(svm_fit, test_2023) %>%
  bind_cols(test_2023 %>% select(site, year, hybrid, yield))

svm_metrics <- metrics(svm_pred_2023, truth = yield, estimate = .pred)
svm_metrics
```


```{r}
#----------CREATING XGBOOST GRAPH-----------
xgb_rmse <- xgb_metrics %>% filter(.metric == "rmse") %>% 
  pull(.estimate)
xgb_rsq  <- xgb_metrics %>% filter(.metric == "rsq") %>% 
  pull(.estimate)

ggplot(xgb_pred_2023, aes(x = yield, y = .pred)) +
  geom_point(alpha = 0.5) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  labs(
    title = "XGBoost: Predicted vs Observed Yield",
    subtitle = paste0("RMSE = ", round(xgb_rmse, 2), " | R² = ", round(xgb_rsq, 3)),
    x = "Observed Yield",
    y = "Predicted Yield"
  ) +
  theme_minimal()
```

```{r}
#----------CREATING RANDOM FOREST GRAPH-----------
rf_rmse <- rf_metrics %>% filter(.metric == "rmse") %>% 
  pull(.estimate)
rf_rsq  <- rf_metrics %>% filter(.metric == "rsq") %>% 
  pull(.estimate)

ggplot(rf_pred_2023, aes(x = yield, y = .pred)) +
  geom_point(alpha = 0.5) +
  geom_abline(slope = 1, intercept = 0, linetype = "dashed") +
  labs(
    title = "Random Forest: Predicted vs Observed Yield",
    subtitle = paste0("RMSE = ", round(rf_rmse, 2), " | R² = ", round(rf_rsq, 3)),
    x = "Observed Yield",
    y = "Predicted Yield"
  ) +
  theme_minimal()
```

```{r}
#----------COMPARING THE TWO MODELS--------------
bind_rows(
  xgb_metrics %>% 
    mutate(model = "XGBoost"),
  rf_metrics %>% 
    mutate(model = "Random Forest")
)
```


